# ICD-10 simple-English explanations for family-facing tooltips.
# Language target: 6th-grade reading level. No jargon. Calm tone.
# hospice_context adds a sentence of reassurance specific to end-of-life care.
#
# Run directly: bin/rails runner db/seeds_icd10.rb

ICD10_SEEDS = [
  # ── Cancer ─────────────────────────────────────────────────────────
  { code: "C18.9", category: "cancer",
    simple: "Cancer of the colon (large intestine).",
    context: "We focus on easing pain, managing nausea, and keeping meals comfortable." },
  { code: "C19", category: "cancer",
    simple: "Cancer where the colon meets the rectum.",
    context: "Comfort care focuses on pain control and bowel comfort." },
  { code: "C22.0", category: "cancer",
    simple: "Liver cancer.",
    context: "We watch for fatigue, swelling, and confusion, and keep the person comfortable." },
  { code: "C25.9", category: "cancer",
    simple: "Pancreatic cancer.",
    context: "We prioritize pain relief and help with appetite and energy." },
  { code: "C34.90", category: "cancer",
    simple: "Lung cancer.",
    context: "We focus on easing shortness of breath and keeping pain under control." },
  { code: "C50.9", category: "cancer",
    simple: "Breast cancer.",
    context: "Comfort care focuses on pain, fatigue, and emotional support for the whole family." },
  { code: "C50.911", category: "cancer",
    simple: "Breast cancer (right side).",
    context: "Comfort care focuses on pain, fatigue, and emotional support for the whole family." },
  { code: "C50.912", category: "cancer",
    simple: "Breast cancer (left side).",
    context: "Comfort care focuses on pain, fatigue, and emotional support for the whole family." },
  { code: "C56.9", category: "cancer",
    simple: "Ovarian cancer.",
    context: "We focus on pain and belly comfort, and keeping energy steady." },
  { code: "C61", category: "cancer",
    simple: "Prostate cancer.",
    context: "We focus on pain management, especially if the cancer has spread to bones." },
  { code: "C64.9", category: "cancer",
    simple: "Kidney cancer.",
    context: "Comfort care watches for pain, fatigue, and swelling." },
  { code: "C67.9", category: "cancer",
    simple: "Bladder cancer.",
    context: "We help with comfort around urination and pain control." },
  { code: "C71.9", category: "cancer",
    simple: "Brain cancer.",
    context: "We watch for headaches, weakness, and confusion, and keep the person calm and comfortable." },
  { code: "C77.9", category: "cancer",
    simple: "Cancer that has spread to lymph nodes.",
    context: "This means the cancer is advanced. We focus on keeping the person comfortable." },
  { code: "C78.00", category: "cancer",
    simple: "Cancer that has spread to the lungs.",
    context: "We focus on easing shortness of breath and supporting restful sleep." },
  { code: "C79.51", category: "cancer",
    simple: "Cancer that has spread to the bones.",
    context: "Bone pain can be strong. We use medicines and gentle positioning to keep pain low." },
  { code: "C90.00", category: "cancer",
    simple: "Multiple myeloma (a blood cancer affecting bones).",
    context: "We focus on pain, fatigue, and preventing falls." },
  { code: "C91.10", category: "cancer",
    simple: "Chronic lymphocytic leukemia (a slow-growing blood cancer).",
    context: "Comfort care focuses on fatigue, infection risk, and emotional support." },
  { code: "C92.10", category: "cancer",
    simple: "Chronic myeloid leukemia (a blood cancer).",
    context: "We focus on fatigue, bleeding risk, and keeping the person comfortable." },
  { code: "C95.90", category: "cancer",
    simple: "Leukemia (a cancer of the blood).",
    context: "We focus on fatigue, bruising, and infection prevention." },

  # ── Cardiac ────────────────────────────────────────────────────────
  { code: "I50.9", category: "cardiac",
    simple: "Heart failure — the heart is not pumping as strongly as it should.",
    context: "This is very common near the end of life. We focus on breathing, swelling, and rest." },
  { code: "I50.22", category: "cardiac",
    simple: "Long-term heart failure (the main pumping chamber is weak).",
    context: "We watch for swelling, tiredness, and shortness of breath, and adjust medicines to keep the person comfortable." },
  { code: "I50.32", category: "cardiac",
    simple: "Long-term heart failure (the heart is stiff and does not fill well).",
    context: "We help manage breathing, fluid buildup, and fatigue." },
  { code: "I25.10", category: "cardiac",
    simple: "Coronary artery disease — the arteries to the heart are narrowed.",
    context: "We watch for chest discomfort and keep the person resting comfortably." },
  { code: "I48.91", category: "cardiac",
    simple: "Atrial fibrillation — an uneven, sometimes fast heartbeat.",
    context: "Usually not painful. We keep an eye on the rhythm and energy level." },
  { code: "I21.3", category: "cardiac",
    simple: "A recent heart attack.",
    context: "We focus on chest comfort, breathing, and rest." },
  { code: "I63.9", category: "cardiac",
    simple: "Stroke caused by a blocked blood vessel in the brain.",
    context: "We help with swallowing, comfort, and communication." },
  { code: "I69.30", category: "cardiac",
    simple: "Lasting effects from a past stroke.",
    context: "We support mobility, swallowing, and comfort." },

  # ── Pulmonary ──────────────────────────────────────────────────────
  { code: "J44.9", category: "pulmonary",
    simple: "COPD — long-term lung disease that makes breathing hard.",
    context: "We focus on easing shortness of breath with medicines, position, and calm." },
  { code: "J96.20", category: "pulmonary",
    simple: "Sudden trouble with the lungs making enough oxygen.",
    context: "We keep the person comfortable with oxygen and gentle medicines." },
  { code: "J84.10", category: "pulmonary",
    simple: "Scarring of the lungs that makes breathing harder over time.",
    context: "We focus on easing breathing and anxiety that comes with it." },
  { code: "J18.9", category: "pulmonary",
    simple: "Pneumonia (a lung infection).",
    context: "Near end of life, pneumonia is common. We focus on comfort rather than aggressive treatment." },
  { code: "J80", category: "pulmonary",
    simple: "A serious lung problem where the lungs fill with fluid.",
    context: "We keep the person comfortable and calm with medicines that ease breathing." },

  # ── Neuro / Dementia ──────────────────────────────────────────────
  { code: "G30.9", category: "neuro",
    simple: "Alzheimer's disease — memory loss that gets worse over time.",
    context: "We focus on a calm routine, gentle care, and moments of connection." },
  { code: "F03.90", category: "neuro",
    simple: "Dementia — lasting memory and thinking changes.",
    context: "We use a calm, familiar environment and gentle touch." },
  { code: "F02.80", category: "neuro",
    simple: "Dementia caused by another condition (like Parkinson's or a stroke).",
    context: "Care focuses on comfort, routine, and reassurance." },
  { code: "G31.83", category: "neuro",
    simple: "Lewy body dementia — memory and movement problems together.",
    context: "We watch for sleep and mood changes, and use gentle medicines when needed." },
  { code: "G20", category: "neuro",
    simple: "Parkinson's disease — affects movement, balance, and sometimes thinking.",
    context: "We focus on safe positioning, swallowing help, and calm surroundings." },
  { code: "G12.21", category: "neuro",
    simple: "ALS (Lou Gehrig's disease) — muscles slowly get weaker.",
    context: "We focus on breathing comfort, swallowing help, and emotional support." },
  { code: "G35", category: "neuro",
    simple: "Multiple sclerosis — affects nerves in the brain and spine.",
    context: "We support mobility, pain, and bladder comfort." },
  { code: "G93.1", category: "neuro",
    simple: "Brain injury from lack of oxygen.",
    context: "Care focuses on comfort, gentle positioning, and family support." },
  { code: "R54", category: "neuro",
    simple: "Weakness and decline that come with aging.",
    context: "We focus on comfort, nutrition as tolerated, and time with loved ones." },

  # ── Kidney / Liver ────────────────────────────────────────────────
  { code: "N18.6", category: "renal",
    simple: "End-stage kidney disease — the kidneys no longer filter the blood.",
    context: "We focus on comfort, gentle fluids, and easing itching or nausea." },
  { code: "N18.5", category: "renal",
    simple: "Very advanced kidney disease (stage 5).",
    context: "We help with fatigue, nausea, and fluid balance." },
  { code: "K74.60", category: "renal",
    simple: "Cirrhosis — long-term liver damage.",
    context: "We watch for swelling, confusion, and bleeding, and keep the person comfortable." },
  { code: "K70.30", category: "renal",
    simple: "Cirrhosis of the liver caused by long-term alcohol use.",
    context: "Care focuses on comfort, nutrition, and emotional support for the family." },
  { code: "K72.90", category: "renal",
    simple: "Liver failure — the liver has stopped doing its job.",
    context: "We manage confusion, swelling, and comfort gently." },

  # ── Infectious / Terminal ─────────────────────────────────────────
  { code: "B20", category: "infectious",
    simple: "Advanced HIV disease.",
    context: "We focus on comfort, infection prevention, and emotional care." },
  { code: "A41.9", category: "infectious",
    simple: "Sepsis — a serious infection throughout the body.",
    context: "At this stage we focus on comfort rather than aggressive treatment." },
  { code: "R65.21", category: "infectious",
    simple: "Severe sepsis with shock — the body is overwhelmed by infection.",
    context: "We keep the person calm and pain-free." },
  { code: "U07.1", category: "infectious",
    simple: "COVID-19 illness.",
    context: "We focus on breathing comfort and gentle care." },

  # ── Debility / Non-specific ───────────────────────────────────────
  { code: "R63.4", category: "debility",
    simple: "Unexplained weight loss.",
    context: "We offer favorite foods as tolerated. Near end of life, appetite naturally decreases." },
  { code: "R64", category: "debility",
    simple: "Severe weight and muscle loss from illness (cachexia).",
    context: "We focus on comfort foods in small amounts, and loving presence." },
  { code: "R62.7", category: "debility",
    simple: "Adult failure to thrive — slow decline in strength, appetite, and energy.",
    context: "We focus on comfort, dignity, and family time." },
  { code: "Z51.5", category: "debility",
    simple: "A visit for comfort care (palliative care).",
    context: "This is care focused on comfort, not on curing the illness." },
  { code: "R26.2", category: "debility",
    simple: "Trouble walking.",
    context: "We help with safe movement, equipment, and preventing falls." },
  { code: "M62.84", category: "debility",
    simple: "Significant muscle loss.",
    context: "We focus on gentle positioning, skin care, and comfort." },
  { code: "R41.82", category: "debility",
    simple: "Changes in how the person thinks or remembers.",
    context: "We keep the environment calm and familiar." },
  { code: "R50.9", category: "debility",
    simple: "Fever without a clear cause.",
    context: "We keep the person cool and comfortable." },
  { code: "R06.02", category: "debility",
    simple: "Shortness of breath.",
    context: "We use position, oxygen, and gentle medicines to ease breathing." },
  { code: "R52", category: "debility",
    simple: "Pain.",
    context: "We aim to keep pain low and stable using safe, effective medicines." }
].freeze

puts "== Seeding ICD-10 simple-English explanations =="
created = 0
updated = 0
ICD10_SEEDS.each do |row|
  rec = Icd10Explanation.find_or_initialize_by(code: row[:code])
  was_new = rec.new_record?
  rec.simple_description = row[:simple]
  rec.hospice_context    = row[:context]
  rec.category           = row[:category]
  rec.save!
  was_new ? created += 1 : updated += 1
end
puts "   created=#{created} updated=#{updated} total=#{Icd10Explanation.count}"
