# One-shot 6-digit sign-in codes emailed to users who prefer not to type
# a password. Generated by PasswordlessController, consumed on first
# successful verification. Hashed at rest (SHA-256) so a DB snapshot
# doesn't leak live codes.
#
# Lifecycle:
#   1. PasswordlessController#create → LoginCode.request_for!(user, ip:)
#      invalidates prior unconsumed codes + creates a fresh one
#   2. UserMailer.login_code.deliver_now sends the plaintext code
#   3. PasswordlessController#consume → LoginCode.consume!(user, plaintext)
#      verifies hash, expiry, and one-shot then stamps consumed_at

class LoginCode < ApplicationRecord
  belongs_to :user

  CODE_TTL     = 15.minutes
  CODE_LENGTH  = 6

  scope :unused, -> { where(consumed_at: nil).where("expires_at > ?", Time.current) }

  # Create a new code for the user. Any previously-issued unconsumed
  # codes are invalidated so the user can only be holding one valid
  # code at a time (limits replay window + prevents "which email was
  # it in" confusion).
  def self.request_for!(user, ip: nil)
    where(user: user, consumed_at: nil).update_all(consumed_at: Time.current)
    plaintext = SecureRandom.random_number(10**CODE_LENGTH).to_s.rjust(CODE_LENGTH, "0")
    create!(
      user:        user,
      code_digest: digest(plaintext),
      expires_at:  CODE_TTL.from_now,
      ip:          ip
    )
    plaintext
  end

  # Find an unconsumed matching code, mark it consumed, and return it.
  # Returns nil when no live code matches — caller should treat that as
  # "invalid or expired".
  def self.consume!(user, plaintext)
    return nil if plaintext.to_s.strip.empty?
    row = unused.where(user: user, code_digest: digest(plaintext)).first
    return nil unless row
    row.update!(consumed_at: Time.current)
    row
  end

  def self.digest(plaintext)
    Digest::SHA256.hexdigest(plaintext.to_s)
  end
end
